{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/zerabyte-x/love.engineering/blob/main/Valentine_template.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**USER Manual**"
      ],
      "metadata": {
        "id": "U5GtLWSYZzlQ"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "* Run the code from the top left corner _ a play button will appear on top left\n",
        "  if you hover your cursor at the code.\n",
        "* Scroll down after running it .\n",
        "* Click on the cover\n",
        "\n"
      ],
      "metadata": {
        "id": "kRDWnYksZGON"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "%%html\n",
        "<!DOCTYPE html>\n",
        "<html lang=\"en\">\n",
        "<head>\n",
        "    <meta charset=\"UTF-8\">\n",
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
        "    <title>Romantic Valentine Card</title>\n",
        "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\n",
        "    <link href=\"https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Pacifico&display=swap\" rel=\"stylesheet\">\n",
        "    <style>\n",
        "        body {\n",
        "            margin: 0;\n",
        "            height: 100vh;\n",
        "            display: flex;\n",
        "            justify-content: center;\n",
        "            align-items: center;\n",
        "            background: linear-gradient(135deg, #ff99cc, #ffccff, #ff99cc);\n",
        "            overflow: hidden;\n",
        "            font-family: 'Dancing Script', cursive;\n",
        "        }\n",
        "\n",
        "        .container {\n",
        "            position: relative;\n",
        "            width: 75%;\n",
        "            max-width: 560px;\n",
        "        }\n",
        "\n",
        "        .envelope {\n",
        "            position: absolute;\n",
        "            top: 50%;\n",
        "            left: 50%;\n",
        "            transform: translate(-50%, -50%);\n",
        "            width: 240px;\n",
        "            height: 160px;\n",
        "            cursor: pointer;\n",
        "            transition: all 0.8s cubic-bezier(0.68, -0.55, 0.265, 1.55);\n",
        "            filter: drop-shadow(0 10px 20px rgba(0,0,0,0.1));\n",
        "            z-index: 1;\n",
        "        }\n",
        "\n",
        "        .envelope-front {\n",
        "            position: absolute;\n",
        "            width: 100%;\n",
        "            height: 100%;\n",
        "            background: linear-gradient(160deg, #ff3860 40%, #ff1493 100%);\n",
        "            clip-path: polygon(0 0, 100% 0, 100% 85%, 50% 100%, 0 85%);\n",
        "            display: flex;\n",
        "            justify-content: center;\n",
        "            align-items: center;\n",
        "            color: #fff;\n",
        "            font-size: 1.8em;\n",
        "            text-align: center;\n",
        "            font-family: 'Pacifico', cursive;\n",
        "        }\n",
        "\n",
        "        .envelope-back {\n",
        "            position: absolute;\n",
        "            width: 85%;\n",
        "            height: 85%%;\n",
        "            background: linear-gradient(45deg, #ff85a2, #ff6090);\n",
        "            transform: translateY(-15px);\n",
        "            border-radius: 4px;\n",
        "        }\n",
        "\n",
        "        .letter {\n",
        "            position: relative;\n",
        "            width: 100%;\n",
        "            height: 0;\n",
        "            background: linear-gradient(135deg, #fff5f5 0%, #ffe6e6 100%);\n",
        "            padding: 0;\n",
        "            border-radius: 15px;\n",
        "            box-shadow: 0 20px 40px rgba(0,0,0,0.15);\n",
        "            z-index: 2;\n",
        "            opacity: 0;\n",
        "            transition: all 1s ease;\n",
        "        }\n",
        "\n",
        "        .letter.open {\n",
        "            height: auto;\n",
        "            padding: 30px;\n",
        "            opacity: 1;\n",
        "        }\n",
        "\n",
        "        .message {\n",
        "            font-family: 'Dancing Script', cursive;\n",
        "            font-size: 1.4em;\n",
        "            color: black;\n",
        "            opacity: 1;\n",
        "            transform: translateY(20px);\n",
        "            transition: all 0.8s ease;\n",
        "        }\n",
        "\n",
        "        .message.show {\n",
        "            opacity: 1;\n",
        "            transform: translateY(0);\n",
        "        }\n",
        "\n",
        "        .smoke-particle {\n",
        "            position: absolute;\n",
        "            width: 8px;\n",
        "            height: 8px;\n",
        "            background: rgba(255,255,255,0.9);\n",
        "            border-radius: 50%;\n",
        "            pointer-events: none;\n",
        "            animation: smoke-drift 4s ease-out forwards;\n",
        "        }\n",
        "\n",
        "        @keyframes smoke-drift {\n",
        "            0% { transform: translateY(0) scale(1); opacity: 1; }\n",
        "            100% { transform: translateY(-100px) scale(3); opacity: 0; }\n",
        "        }\n",
        "\n",
        "        .floating-item {\n",
        "            position: fixed;\n",
        "            pointer-events: none;\n",
        "            animation: float 6s ease-in-out infinite;\n",
        "        }\n",
        "\n",
        "        @keyframes float {\n",
        "            0%, 100% { transform: translateY(0) rotate(-5deg); }\n",
        "            50% { transform: translateY(-20px) rotate(5deg); }\n",
        "        }\n",
        "    </style>\n",
        "</head>\n",
        "<body>\n",
        "    <div class=\"container\">\n",
        "        <div class=\"envelope\" onclick=\"toggleEnvelope()\">\n",
        "            <div class=\"envelope-back\"></div>\n",
        "            <div class=\"envelope-front\">\n",
        "                To,<br>My love ❤️\n",
        "            </div>\n",
        "        </div>\n",
        "        <div class=\"letter\">\n",
        "            <div class=\"message\">\n",
        "                <h1> Hey ❤️, </h1>\n",
        "                <p>.......✨.</p>\n",
        "                <p>....... but I promise I'm paying attention.</p>\n",
        "                <p>But I'm pretty good at one thing - knowing that you're my favorite part of every single day 💫.</p>\n",
        "                <p>I'm out of words...🤍.</p>\n",
        "                <p>Yours,</p>\n",
        "                <p>Utkarsh</p>\n",
        "                <p>P.S. Happy Valentine's Day, my favorite person 💝</p>\n",
        "            </div>\n",
        "        </div>\n",
        "    </div>\n",
        "\n",
        "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js\"></script>\n",
        "    <script>\n",
        "        let isOpen = false;\n",
        "        let smokeParticles = [];\n",
        "        let floatingInterval;\n",
        "\n",
        "        function toggleEnvelope() {\n",
        "            if (!isOpen) {\n",
        "                createSmoke();\n",
        "                createFloatingItems();\n",
        "\n",
        "                anime({\n",
        "                    targets: '.envelope',\n",
        "                    top: '-120px',\n",
        "                    left: '-120px',\n",
        "                    rotate: '-20deg',\n",
        "                    easing: 'easeInOutQuad',\n",
        "                    duration: 1000\n",
        "                });\n",
        "\n",
        "                anime({\n",
        "                    targets: '.letter',\n",
        "                    height: 'auto',\n",
        "                    padding: '30px',\n",
        "                    opacity: 1,\n",
        "                    easing: 'easeInOutQuad',\n",
        "                    duration: 1000\n",
        "                });\n",
        "\n",
        "                anime({\n",
        "                    targets: '.message > *',\n",
        "                    opacity: [0, 1],\n",
        "                    translateY: [20, 0],\n",
        "                    delay: anime.stagger(100),\n",
        "                    easing: 'easeOutElastic(1, .8)'\n",
        "                });\n",
        "\n",
        "                document.querySelector('.letter').classList.add('open');\n",
        "                document.querySelectorAll('.message > *').forEach(element => element.classList.add('show'));\n",
        "\n",
        "                isOpen = true;\n",
        "            } else {\n",
        "                anime({\n",
        "                    targets: '.message > *',\n",
        "                    opacity: [1, 0],\n",
        "                    translateY: [0, 20],\n",
        "                    delay: anime.stagger(100),\n",
        "                    easing: 'easeInElastic(1, .8)'\n",
        "                });\n",
        "\n",
        "                anime({\n",
        "                    targets: '.envelope',\n",
        "                    top: '50%',\n",
        "                    left: '50%',\n",
        "                    rotate: '0deg',\n",
        "                    easing: 'easeInOutQuad',\n",
        "                    duration: 1000\n",
        "                });\n",
        "\n",
        "                anime({\n",
        "                    targets: '.letter',\n",
        "                    height: '0',\n",
        "                    padding: '0',\n",
        "                    opacity: 0,\n",
        "                    easing: 'easeInOutQuad',\n",
        "                    duration: 1000\n",
        "                });\n",
        "\n",
        "                document.querySelector('.letter').classList.remove('open');\n",
        "                document.querySelectorAll('.message > *').forEach(element => element.classList.remove('show'));\n",
        "\n",
        "                removeSmoke();\n",
        "                stopFloatingItems();\n",
        "                isOpen = false;\n",
        "            }\n",
        "        }\n",
        "\n",
        "        function createSmoke() {\n",
        "            for(let i = 0; i < 15; i++) {\n",
        "                const smoke = document.createElement('div');\n",
        "                smoke.className = 'smoke-particle';\n",
        "                smoke.style.left = `${50 + Math.random() * 20 - 10}%`;\n",
        "                smoke.style.top = '50%';\n",
        "                smoke.style.animationDelay = `${i * 0.1}s`;\n",
        "                document.body.appendChild(smoke);\n",
        "                smokeParticles.push(smoke);\n",
        "            }\n",
        "        }\n",
        "\n",
        "        function removeSmoke() {\n",
        "            smokeParticles.forEach(smoke => smoke.remove());\n",
        "            smokeParticles = [];\n",
        "        }\n",
        "\n",
        "        function createFloatingItems() {\n",
        "            const items = ['❤️', '💕', '✨', '💗', '💓', '💞', '😘', '😍', '😘'];\n",
        "            floatingInterval = setInterval(() => {\n",
        "                const item = items[Math.floor(Math.random() * items.length)];\n",
        "                createFloatingItem(item);\n",
        "            }, 400);\n",
        "        }\n",
        "\n",
        "        function createFloatingItem(content) {\n",
        "            const item = document.createElement('div');\n",
        "            item.className = 'floating-item animate__animated animate__heartBeat';\n",
        "            item.style.left = Math.random() * 100 + 'vw';\n",
        "            item.style.top = Math.random() * 100 + 'vh';\n",
        "            item.style.fontSize = (Math.random() * 20 + 20) + 'px';\n",
        "            item.innerHTML = content;\n",
        "\n",
        "            if(!['❤️', '💕', '✨'].includes(content)) {\n",
        "                item.style.fontFamily = 'Pacifico, cursive';\n",
        "                item.style.color = '#ff1493';\n",
        "            }\n",
        "\n",
        "            document.body.appendChild(item);\n",
        "            setTimeout(() => item.remove(), 5000);\n",
        "        }\n",
        "\n",
        "        function stopFloatingItems() {\n",
        "            clearInterval(floatingInterval);\n",
        "            document.querySelectorAll('.floating-item').forEach(item => item.remove());\n",
        "        }\n",
        "    </script>\n",
        "</body>\n",
        "</html>\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "q9m9GdVGR7vR",
        "outputId": "780b4839-78a6-49f3-b82b-5a682496bd3e"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "<!DOCTYPE html>\n",
              "<html lang=\"en\">\n",
              "<head>\n",
              "    <meta charset=\"UTF-8\">\n",
              "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
              "    <title>Romantic Valentine Card</title>\n",
              "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\n",
              "    <link href=\"https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Pacifico&display=swap\" rel=\"stylesheet\">\n",
              "    <style>\n",
              "        body {\n",
              "            margin: 0;\n",
              "            height: 100vh;\n",
              "            display: flex;\n",
              "            justify-content: center;\n",
              "            align-items: center;\n",
              "            background: linear-gradient(135deg, #ff99cc, #ffccff, #ff99cc);\n",
              "            overflow: hidden;\n",
              "            font-family: 'Dancing Script', cursive;\n",
              "        }\n",
              "\n",
              "        .container {\n",
              "            position: relative;\n",
              "            width: 75%;\n",
              "            max-width: 560px;\n",
              "        }\n",
              "\n",
              "        .envelope {\n",
              "            position: absolute;\n",
              "            top: 50%;\n",
              "            left: 50%;\n",
              "            transform: translate(-50%, -50%);\n",
              "            width: 240px;\n",
              "            height: 160px;\n",
              "            cursor: pointer;\n",
              "            transition: all 0.8s cubic-bezier(0.68, -0.55, 0.265, 1.55);\n",
              "            filter: drop-shadow(0 10px 20px rgba(0,0,0,0.1));\n",
              "            z-index: 1;\n",
              "        }\n",
              "\n",
              "        .envelope-front {\n",
              "            position: absolute;\n",
              "            width: 100%;\n",
              "            height: 100%;\n",
              "            background: linear-gradient(160deg, #ff3860 40%, #ff1493 100%);\n",
              "            clip-path: polygon(0 0, 100% 0, 100% 85%, 50% 100%, 0 85%);\n",
              "            display: flex;\n",
              "            justify-content: center;\n",
              "            align-items: center;\n",
              "            color: #fff;\n",
              "            font-size: 1.8em;\n",
              "            text-align: center;\n",
              "            font-family: 'Pacifico', cursive;\n",
              "        }\n",
              "\n",
              "        .envelope-back {\n",
              "            position: absolute;\n",
              "            width: 85%;\n",
              "            height: 85%%;\n",
              "            background: linear-gradient(45deg, #ff85a2, #ff6090);\n",
              "            transform: translateY(-15px);\n",
              "            border-radius: 4px;\n",
              "        }\n",
              "\n",
              "        .letter {\n",
              "            position: relative;\n",
              "            width: 100%;\n",
              "            height: 0;\n",
              "            background: linear-gradient(135deg, #fff5f5 0%, #ffe6e6 100%);\n",
              "            padding: 0;\n",
              "            border-radius: 15px;\n",
              "            box-shadow: 0 20px 40px rgba(0,0,0,0.15);\n",
              "            z-index: 2;\n",
              "            opacity: 0;\n",
              "            transition: all 1s ease;\n",
              "        }\n",
              "\n",
              "        .letter.open {\n",
              "            height: auto;\n",
              "            padding: 30px;\n",
              "            opacity: 1;\n",
              "        }\n",
              "\n",
              "        .message {\n",
              "            font-family: 'Dancing Script', cursive;\n",
              "            font-size: 1.4em;\n",
              "            color: black;\n",
              "            opacity: 1;\n",
              "            transform: translateY(20px);\n",
              "            transition: all 0.8s ease;\n",
              "        }\n",
              "\n",
              "        .message.show {\n",
              "            opacity: 1;\n",
              "            transform: translateY(0);\n",
              "        }\n",
              "\n",
              "        .smoke-particle {\n",
              "            position: absolute;\n",
              "            width: 8px;\n",
              "            height: 8px;\n",
              "            background: rgba(255,255,255,0.9);\n",
              "            border-radius: 50%;\n",
              "            pointer-events: none;\n",
              "            animation: smoke-drift 4s ease-out forwards;\n",
              "        }\n",
              "\n",
              "        @keyframes smoke-drift {\n",
              "            0% { transform: translateY(0) scale(1); opacity: 1; }\n",
              "            100% { transform: translateY(-100px) scale(3); opacity: 0; }\n",
              "        }\n",
              "\n",
              "        .floating-item {\n",
              "            position: fixed;\n",
              "            pointer-events: none;\n",
              "            animation: float 6s ease-in-out infinite;\n",
              "        }\n",
              "\n",
              "        @keyframes float {\n",
              "            0%, 100% { transform: translateY(0) rotate(-5deg); }\n",
              "            50% { transform: translateY(-20px) rotate(5deg); }\n",
              "        }\n",
              "    </style>\n",
              "</head>\n",
              "<body>\n",
              "    <div class=\"container\">\n",
              "        <div class=\"envelope\" onclick=\"toggleEnvelope()\">\n",
              "            <div class=\"envelope-back\"></div>\n",
              "            <div class=\"envelope-front\">\n",
              "                To,<br>My love ❤️\n",
              "            </div>\n",
              "        </div>\n",
              "        <div class=\"letter\">\n",
              "            <div class=\"message\">\n",
              "                <h1> Hey ❤️, </h1>\n",
              "                <p>.......✨.</p>\n",
              "                <p>....... but I promise I'm paying attention.</p>\n",
              "                <p>But I'm pretty good at one thing - knowing that you're my favorite part of every single day 💫.</p>\n",
              "                <p>I'm out of words...🤍.</p>\n",
              "                <p>Yours,</p>\n",
              "                <p>Utkarsh</p>\n",
              "                <p>P.S. Happy Valentine's Day, my favorite person 💝</p>\n",
              "            </div>\n",
              "        </div>\n",
              "    </div>\n",
              "\n",
              "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js\"></script>\n",
              "    <script>\n",
              "        let isOpen = false;\n",
              "        let smokeParticles = [];\n",
              "        let floatingInterval;\n",
              "\n",
              "        function toggleEnvelope() {\n",
              "            if (!isOpen) {\n",
              "                createSmoke();\n",
              "                createFloatingItems();\n",
              "\n",
              "                anime({\n",
              "                    targets: '.envelope',\n",
              "                    top: '-120px',\n",
              "                    left: '-120px',\n",
              "                    rotate: '-20deg',\n",
              "                    easing: 'easeInOutQuad',\n",
              "                    duration: 1000\n",
              "                });\n",
              "\n",
              "                anime({\n",
              "                    targets: '.letter',\n",
              "                    height: 'auto',\n",
              "                    padding: '30px',\n",
              "                    opacity: 1,\n",
              "                    easing: 'easeInOutQuad',\n",
              "                    duration: 1000\n",
              "                });\n",
              "\n",
              "                anime({\n",
              "                    targets: '.message > *',\n",
              "                    opacity: [0, 1],\n",
              "                    translateY: [20, 0],\n",
              "                    delay: anime.stagger(100),\n",
              "                    easing: 'easeOutElastic(1, .8)'\n",
              "                });\n",
              "\n",
              "                document.querySelector('.letter').classList.add('open');\n",
              "                document.querySelectorAll('.message > *').forEach(element => element.classList.add('show'));\n",
              "\n",
              "                isOpen = true;\n",
              "            } else {\n",
              "                anime({\n",
              "                    targets: '.message > *',\n",
              "                    opacity: [1, 0],\n",
              "                    translateY: [0, 20],\n",
              "                    delay: anime.stagger(100),\n",
              "                    easing: 'easeInElastic(1, .8)'\n",
              "                });\n",
              "\n",
              "                anime({\n",
              "                    targets: '.envelope',\n",
              "                    top: '50%',\n",
              "                    left: '50%',\n",
              "                    rotate: '0deg',\n",
              "                    easing: 'easeInOutQuad',\n",
              "                    duration: 1000\n",
              "                });\n",
              "\n",
              "                anime({\n",
              "                    targets: '.letter',\n",
              "                    height: '0',\n",
              "                    padding: '0',\n",
              "                    opacity: 0,\n",
              "                    easing: 'easeInOutQuad',\n",
              "                    duration: 1000\n",
              "                });\n",
              "\n",
              "                document.querySelector('.letter').classList.remove('open');\n",
              "                document.querySelectorAll('.message > *').forEach(element => element.classList.remove('show'));\n",
              "\n",
              "                removeSmoke();\n",
              "                stopFloatingItems();\n",
              "                isOpen = false;\n",
              "            }\n",
              "        }\n",
              "\n",
              "        function createSmoke() {\n",
              "            for(let i = 0; i < 15; i++) {\n",
              "                const smoke = document.createElement('div');\n",
              "                smoke.className = 'smoke-particle';\n",
              "                smoke.style.left = `${50 + Math.random() * 20 - 10}%`;\n",
              "                smoke.style.top = '50%';\n",
              "                smoke.style.animationDelay = `${i * 0.1}s`;\n",
              "                document.body.appendChild(smoke);\n",
              "                smokeParticles.push(smoke);\n",
              "            }\n",
              "        }\n",
              "\n",
              "        function removeSmoke() {\n",
              "            smokeParticles.forEach(smoke => smoke.remove());\n",
              "            smokeParticles = [];\n",
              "        }\n",
              "\n",
              "        function createFloatingItems() {\n",
              "            const items = ['❤️', '💕', '✨', '💗', '💓', '💞', '😘', '😍', '😘'];\n",
              "            floatingInterval = setInterval(() => {\n",
              "                const item = items[Math.floor(Math.random() * items.length)];\n",
              "                createFloatingItem(item);\n",
              "            }, 400);\n",
              "        }\n",
              "\n",
              "        function createFloatingItem(content) {\n",
              "            const item = document.createElement('div');\n",
              "            item.className = 'floating-item animate__animated animate__heartBeat';\n",
              "            item.style.left = Math.random() * 100 + 'vw';\n",
              "            item.style.top = Math.random() * 100 + 'vh';\n",
              "            item.style.fontSize = (Math.random() * 20 + 20) + 'px';\n",
              "            item.innerHTML = content;\n",
              "\n",
              "            if(!['❤️', '💕', '✨'].includes(content)) {\n",
              "                item.style.fontFamily = 'Pacifico, cursive';\n",
              "                item.style.color = '#ff1493';\n",
              "            }\n",
              "\n",
              "            document.body.appendChild(item);\n",
              "            setTimeout(() => item.remove(), 5000);\n",
              "        }\n",
              "\n",
              "        function stopFloatingItems() {\n",
              "            clearInterval(floatingInterval);\n",
              "            document.querySelectorAll('.floating-item').forEach(item => item.remove());\n",
              "        }\n",
              "    </script>\n",
              "</body>\n",
              "</html>\n"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}